### ISSUE TITLE
Error: Cannot find module 'asciidoctor.js on first try

### ISSUE THREAD

**Issue by GabLeRoux** [debrouwere/yaml2json#1]
```
$ nvm use stable         
Now using node v7.7.2 (npm v4.1.2)
```

```bash
$ npm i -g yaml-to-json
$ which yaml2json
~/.nvm/versions/node/v7.7.2/bin/yaml2json
```

```bash
$ yaml2json
Error: Cannot find module 'asciidoctor.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/gableroux/.npm-global/lib/node_modules/yaml-to-json/lib/markup.js:12:15)
    at Object.<anonymous> (/home/gableroux/.npm-global/lib/node_modules/yaml-to-json/lib/markup.js:84:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

**Comment by mxweaver** [comment]
I also ran into this issue when attempting to run `./node_modules/.bin/yaml2json <filename>`. This error does not occur when running `yaml2json` from a global install.

**Comment by b-long** [comment]
I don't think that's correct @mayacifelli .  Perhaps on your machine `asciidoctor.js` was installed to the global `node_modules` directory?

**Comment by xenogenesi** [comment]
I'm installing yaml2json globally and it fail to run because of missing `asciidoctor.js`, the problem is it depends on a too old version of asciidoctor, see https://github.com/asciidoctor/asciidoctor.js/issues/172 and https://github.com/asciidoctor/asciidoctor.js/issues/174
