### ISSUE TITLE
TypeError: Cannot read property 'hash2' of undefined

### ISSUE THREAD

**Issue by gregolsky** [debrouwere/yaml2json#4]
```
λ  yaml2json.cmd --help
C:\Users\grego\AppData\Roaming\nvm\v8.9.4\node_modules\yaml-to-json\lib\markup.js:17
  asciidocOptions = Opal.hash2(['doctype', 'attributes'], {
                         ^

TypeError: Cannot read property 'hash2' of undefined
    at Object.<anonymous> (C:\Users\grego\AppData\Roaming\nvm\v8.9.4\node_modules\yaml-to-json\lib\markup.js:17:26)
    at Object.<anonymous> (C:\Users\grego\AppData\Roaming\nvm\v8.9.4\node_modules\yaml-to-json\lib\markup.js:84:4)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\grego\AppData\Roaming\nvm\v8.9.4\node_modules\yaml-to-json\lib\command.js:17:12)
```

**Comment by libasoles** [comment]
Same here. No news?
It's something about this library:
https://github.com/opal/opal-node
